<a href="https://colab.research.google.com/github/priyarane879/Employee-Attrition-Analysis/blob/main/SQL_Capstone_1_Part_2(Priya_Naik).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Capstone 1 - Part 2

In the first part of the capstone, we focused on Data Retrieval, Data Preprocessing, Feature Engineering and Exploratory Data Analysis using Python & its libraries. Now we are going to shift gears and gain insights into our HR Analytics dataset using SQL.

## TODO: Make use of SQL to do the following:

### Create a SQLITE3 DB using the CSV file (2 pts). Please refer this [link](https://www.linkedin.com/pulse/accessing-sqlite3-database-from-jupyter-notebook-using-varun-lobo/) and this [link](https://www.geeksforgeeks.org/how-to-import-csv-file-in-sqlite-database-using-python/) to know more.

### Calculate the Attrition Rate and summarize attrition (3 pts) by:
- Gender
- Department
- Age
- Average monthly income by job level
- Years at company

### Continue using SQL to explore main reasons for attrition (3 pts), For example:
- Why do more people over 50 years old leave the company than people who aged 40-50?
- Why do people with higher pay still leave the company?
- Which factors drive employees who work at company less than 5 years to leave?

### Effective Communication (2 pts)
- Please make use of markdown cells to communicate your thought process, why did you think of performing a step? what was the observation from the query? etc.
- The code should be commented so that it is readable for the reviewer.

### Grading and Important Instructions
- Each of the above steps are mandatory and should be completed in good faith
- Make sure before submitting that the code is in fully working condition
- It is fine to make use of ChatGPT, stackoverflow type resources, just provide the reference links from where you got it
- Debugging is an art, if you find yourself stuck with errors, take help of stackoverflow and ChatGPT to resolve the issue and if it's still unresolved, reach out to me for help.
- You need to score atleast 7/10 to pass the project, anything less than that will be marked required, needing resubmission.
- Feedback will be provided on 3 levels (Awesome, Suggestion, & Required). Required changes are mandatory to be made.
- For submission, please upload the project on github and share the link to the file with us through LMS.

#### Calculate Attrition Rate

In [1]:
import csv
import sqlite3
import pandas as pd
import sql

In [2]:
!pip install db-sqlite3
!pip install pandasql

Collecting db-sqlite3
  Downloading db-sqlite3-0.0.1.tar.gz (1.4 kB)
  Preparing metadata (setup.py) ... done
Collecting db (from db-sqlite3)
  Downloading db-0.1.1.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... done
Collecting antiorm (from db->db-sqlite3)
  Downloading antiorm-1.2.1.tar.gz (171 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 3.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: db-sqlite3, db, antiorm
  Building wheel for db-sqlite3 (setup.py) ... done
  Created wheel for db-sqlite3: filename=db_sqlite3-0.0.1-py3-none-any.whl size=1769 sha256=11c78772bdffbe0ef6a6bc6e499c7c1a56013b1cdb9b80a49713a2ec505e0f11
  Stored in directory: /root/.cache/pip/wheels/d2/76/f8/d078e1609571cb2d847296a2bb130a355498554aa647e957ba
  Building wheel for db (setup.py) ... done
  Created wheel for db: filename=db-0.1.1-py3-none-any.whl size=3874 sha256=79377faf33bc03b02946810be1a18a8f099c38b6ca691525fb06663846ff292d
  Stored in directory: /root/.cache/pip/wheels/1f/a9/df/8e343ae1489f35fa96888200ee3340217512b98bed2c2def2d
  Building wheel for antiorm (setup.py) ... done
  Created wheel for antiorm: filename=antiorm-1.2.1-py3-none-any.whl size=31665 sha256=b840b17b72c669a889cfba55559dc6b083391b995c9a0828c88e1d0d72d390c6
  Stored in directory: /root/.cache/pip/wheels/71/04/d9/c9b4297ae902eb961bc1cff29b248a7e706693200ef2656fb2
Successfully built db-sqlite3 db antiorm
Installing collected packages: antiorm, db, db-sqlite3
Successfully installed antiorm-1.2.1 db-0.1.1 db-sqlite3-0.0.1
Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pandasql) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (from pandasql) (2.0.38)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->pandasql) (2025.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy->pandasql) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy->pandasql) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26772 sha256=9da237dbd1ee19a2780c3ee95233050df934615193fd219d056c28949e3e55ba
  Stored in directory: /root/.cache/pip/wheels/68/5d/a5/edc271b998f909801d7956959f699b976cc9896075dc47c153
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [3]:
### Implement code
#connecting with the google drive for reading the file from drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
'EnvironmentSatisfaction','OverTime', 'PercentSalaryHike', 'PerformanceRating',\
       'RelationshipSatisfaction','JobSatisfaction','MonthlyIncome','WorkLifeBalance','NumCompaniesWorked','PerformanceRating','YearsSinceLastPromotion'

('EnvironmentSatisfaction',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'JobSatisfaction',
 'MonthlyIncome',
 'WorkLifeBalance',
 'NumCompaniesWorked',
 'PerformanceRating',
 'YearsSinceLastPromotion')

In [5]:
try:

    # Import csv and extract data
    with open('/content/drive/MyDrive/Elevate Pro/SQL/HR-Analytics.csv', 'r') as fin:
        dr = csv.DictReader(fin)



        employee_info = [(i['Attrition'], i['BusinessTravel'],i['\ufeffAge'],i['DailyRate'],i['Department'],i['DistanceFromHome'],i['Education'],
                          i['EducationField'], i['EnvironmentSatisfaction'],i['Gender'],i['HourlyRate'],i['JobInvolvement'],i['JobLevel'],
                          i['JobRole'],i['JobSatisfaction'], i['MaritalStatus'],i['MonthlyIncome'],
                          i['MonthlyRate'],i['NumCompaniesWorked'],i['Over18'],i['OverTime'],i['PercentSalaryHike'],i['PerformanceRating'],
                          i['RelationshipSatisfaction'],i['StandardHours'],i['StockOptionLevel'],i['TotalWorkingYears'],i['TrainingTimesLastYear'],
                          i['WorkLifeBalance'],i['YearsAtCompany'],i['YearsInCurrentRole'],i['YearsSinceLastPromotion'],i['YearsWithCurrManager']
                          )for i in dr]
        print(employee_info)

    # Connect to SQLite
    sqliteConnection = sqlite3.connect('sql.db')
    #sqliteConnection = sqlite3.connect('sql.db')
    cursor = sqliteConnection.cursor()

    # Create student table
    # cursor.execute('create table table_HR(Gender varchar2(10),Department varchar2(10), \
    # Age int,MonthlyIncome int,YearsAtCompany int,Attrition Boolean(10),JobLevel int);')
    cursor.execute('create table table_HR( Age INT, Attrition VARCHAR(3), BusinessTravel VARCHAR(50), DailyRate int, \
    Department VARCHAR(100),DistanceFromHome INT, Education INT, EducationField VARCHAR(100), \
    EnvironmentSatisfaction INT, Gender VARCHAR(10),  HourlyRate INT, JobInvolvement INT, JobLevel INT, JobRole VARCHAR(100),\
    JobSatisfaction INT, MaritalStatus VARCHAR(20), MonthlyIncome INT, MonthlyRate INT, NumCompaniesWorked INT, Over18 VARCHAR(3),OverTime VARCHAR(3),\
    PercentSalaryHike INT,PerformanceRating INT, RelationshipSatisfaction INT,  StandardHours INT, StockOptionLevel INT, TotalWorkingYears INT,\
    TrainingTimesLastYear INT, WorkLifeBalance INT, YearsAtCompany INT, YearsInCurrentRole INT, YearsSinceLastPromotion INT, YearsWithCurrManager INT);')

    # Insert data into table
    cursor.executemany(
        "insert into table_HR ('Attrition', 'BusinessTravel', 'Age','DailyRate', 'Department',\
       'DistanceFromHome', 'Education', 'EducationField',\
        'EnvironmentSatisfaction', 'Gender', 'HourlyRate',\
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',\
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',\
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',\
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',\
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',\
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',\
       'YearsWithCurrManager') VALUES (?, ?,?,?,?,?,?,?, ?,?,?,?,?,?,?, ?,?,?,?,?,?,?, ?,?,?,?,?,?,?, ?,?,?,?);", employee_info)

    # Show student table
    print("done with data")
    cursor.execute('select * from table_HR;')

    # View result
    result = cursor.fetchall()
    print(result)

    # Commit work and close connection
    sqliteConnection.commit()
    cursor.close()

except sqlite3.Error as error:
    print('Error occurred - ', error)

finally:
    if sqliteConnection:
        sqliteConnection.close()
        print('SQLite Connection closed')

[('Yes', 'Travel_Rarely', '41', '1102', 'Sales', '1', '2', 'Life Sciences', '2', 'Female', '94', '3', '2', 'Sales Executive', '4', 'Single', '5993', '19479', '8', 'Y', 'Yes', '11', '3', '1', '80', '0', '8', '0', '1', '6', '4', '0', '5'), ('No', 'Travel_Frequently', '49', '279', 'Research & Development', '8', '1', 'Life Sciences', '3', 'Male', '61', '2', '2', 'Research Scientist', '2', 'Married', '5130', '24907', '1', 'Y', 'No', '23', '4', '4', '80', '1', '10', '3', '3', '10', '7', '1', '7'), ('Yes', 'Travel_Rarely', '37', '1373', 'Research & Development', '2', '2', 'Other', '4', 'Male', '92', '2', '1', 'Laboratory Technician', '3', 'Single', '2090', '2396', '6', 'Y', 'Yes', '15', '3', '2', '80', '0', '7', '3', '3', '0', '0', '0', '0'), ('No', 'Travel_Frequently', '33', '1392', 'Research & Development', '3', '4', 'Life Sciences', '4', 'Female', '56', '3', '1', 'Research Scientist', '3', 'Married', '2909', '23159', '1', 'Y', 'Yes', '11', '3', '3', '80', '0', '8', '3', '3', '8', '7', '3', '0'), ('No', 'Travel_Rarely', '27', '591', 'Research & Development', '2', '1', 'Medical', '1', 'Male', '40', '3', '1', 'Laboratory Technician', '2', 'Married', '3468', '16632', '9', 'Y', 'No', '12', '3', '4', '80', '1', '6', '3', '3', '2', '2', '2', '2'), ('No', 'Travel_Frequently', '32', '1005', 'Research & Development', '2', '2', 'Life Sciences', '4', 'Male', '79', '3', '1', 'Laboratory Technician', '4', 'Single', '3068', '11864', '0', 'Y', 'No', '13', '3', '3', '80', '0', '8', '2', '2', '7', '7', '3', '6'), ('No', 'Travel_Rarely', '59', '1324', 'Research & Development', '3', '3', 'Medical', '3', 'Female', '81', '4', '1', 'Laboratory Technician', '1', 'Married', '2670', '9964', '4', 'Y', 'Yes', '20', '4', '1', '80', '3', '12', '3', '2', '1', '0', '0', '0'), ('No', 'Travel_Rarely', '30', '1358', 'Research & Development', '24', '1', 'Life Sciences', '4', 'Male', '67', '3', '1', 'Laboratory Technician', '3', 'Divorced', '2693', '13335', '1', 'Y', 'No', '22', '4', '2', '80', '1', '1', '2', '3', '1', '0', '0', '0'), ('No', 'Travel_Frequently', '38', '216', 'Research & Development', '23', '3', 'Life Sciences', '4', 'Male', '44', '2', '3', 'Manufacturing Director', '3', 'Single', '9526', '8787', '0', 'Y', 'No', '21', '4', '2', '80', '0', '10', '2', '3', '9', '7', '1', '8'), ('No', 'Travel_Rarely', '36', '1299', 'Research & Development', '27', '3', 'Medical', '3', 'Male', '94', '3', '2', 'Healthcare Representative', '3', 'Married', '5237', '16577', '6', 'Y', 'No', '13', '3', '2', '80', '2', '17', '3', '2', '7', '7', '7', '7'), ('No', 'Travel_Rarely', '35', '809', 'Research & Development', '16', '3', 'Medical', '1', 'Male', '84', '4', '1', 'Laboratory Technician', '2', 'Married', '2426', '16479', '0', 'Y', 'No', '13', '3', '3', '80', '1', '6', '5', '3', '5', '4', '0', '3'), ('No', 'Travel_Rarely', '29', '153', 'Research & Development', '15', '2', 'Life Sciences', '4', 'Female', '49', '2', '2', 'Laboratory Technician', '3', 'Single', '4193', '12682', '0', 'Y', 'Yes', '12', '3', '4', '80', '0', '10', '3', '3', '9', '5', '0', '8'), ('No', 'Travel_Rarely', '31', '670', 'Research & Development', '26', '1', 'Life Sciences', '1', 'Male', '31', '3', '1', 'Research Scientist', '3', 'Divorced', '2911', '15170', '1', 'Y', 'No', '17', '3', '4', '80', '1', '5', '1', '2', '5', '2', '4', '3'), ('No', 'Travel_Rarely', '34', '1346', 'Research & Development', '19', '2', 'Medical', '2', 'Male', '93', '3', '1', 'Laboratory Technician', '4', 'Divorced', '2661', '8758', '0', 'Y', 'No', '11', '3', '3', '80', '1', '3', '2', '3', '2', '2', '1', '2'), ('Yes', 'Travel_Rarely', '28', '103', 'Research & Development', '24', '3', 'Life Sciences', '3', 'Male', '50', '2', '1', 'Laboratory Technician', '3', 'Single', '2028', '12947', '5', 'Y', 'Yes', '14', '3', '2', '80', '0', '6', '4', '3', '4', '2', '0', '3'), ('No', 'Travel_Rarely', '29', '1389', 'Research & Development', '21', '4', 'Life Sciences', '2', 'Female', '51', '4', '3', 'Manufacturing Director', '1', 'Divorced', '9980', '10195', '1', 'Y', 'No', '11', '3', '3', '80', '1', '10', '1', '3', '10', '9', '8', '8'), ('No', 'Travel_Rarely', '32', '334', 'Research & Development', '5', '2', 'Life Sciences', '1', 'Male', '80', '4', '1', 'Research Scientist', '2', 'Divorced', '3298', '15053', '0', 'Y', 'Yes', '12', '3', '4', '80', '2', '7', '5', '2', '6', '2', '0', '5'), ('No', 'Non-Travel', '22', '1123', 'Research & Development', '16', '2', 'Medical', '4', 'Male', '96', '4', '1', 'Laboratory Technician', '4', 'Divorced', '2935', '7324', '1', 'Y', 'Yes', '13', '3', '2', '80', '2', '1', '2', '2', '1', '0', '0', '0'), ('No', 'Travel_Rarely', '53', '1219', 'Sales', '2', '4', 'Life Sciences', '1', 'Female', '78', '2', '4', 'Manager', '4', 'Married', '15427', '22021', '2', 'Y', 'No', '16', '3', '3', '80', '0', '31', '3', '3', '25', '8', '3', '7'), ('No', 'Travel_Rarely', '38', '371', 'Research & Development', '2', '3', 'Life Sciences', '4', 'Male', '45', '3', '1', 'Research Scientist', '4', 'Single', '3944', '4306', '5', 'Y', 'Yes', '11', '3', '3', '80', '0', '6', '3', '3', '3', '2', '1', '2'), ('No', 'Non-Travel', '24', '673', 'Research & Development', '11', '2', 'Other', '1', 'Female', '96', '4', '2', 'Manufacturing Director', '3', 'Divorced', '4011', '8232', '0', 'Y', 'No', '18', '3', '4', '80', '1', '5', '5', '2', '4', '2', '1', '3'), ('Yes', 'Travel_Rarely', '36', '1218', 'Sales', '9', '4', 'Life Sciences', '3', 'Male', '82', '2', '1', 'Sales Representative', '1', 'Single', '3407', '6986', '7', 'Y', 'No', '23', '4', '2', '80', '0', '10', '4', '3', '5', '3', '0', '3'), ('No', 'Travel_Rarely', '34', '419', 'Research & Development', '7', '4', 'Life Sciences', '1', 'Female', '53', '3', '3', 'Research Director', '2', 'Single', '11994', '21293', '0', 'Y', 'No', '11', '3', '3', '80', '0', '13', '4', '3', '12', '6', '2', '11'), ('No', 'Travel_Rarely', '21', '391', 'Research & Development', '15', '2', 'Life Sciences', '3', 'Male', '96', '3', '1', 'Research Scientist', '4', 'Single', '1232', '19281', '1', 'Y', 'No', '14', '3', '4', '80', '0', '0', '6', '3', '0', '0', '0', '0'), ('Yes', 'Travel_Rarely', '34', '699', 'Research & Development', '6', '1', 'Medical', '2', 'Male', '83', '3', '1', 'Research Scientist', '1', 'Single', '2960', '17102', '2', 'Y', 'No', '11', '3', '3', '80', '0', '8', '2', '3', '4', '2', '1', '3'), ('No', 'Travel_Rarely', '53', '1282', 'Research & Development', '5', '3', 'Other', '3', 'Female', '58', '3', '5', 'Manager', '3', 'Divorced', '19094', '10735', '4', 'Y', 'No', '11', '3', '4', '80', '1', '26', '3', '2', '14', '13', '4', '8'), ('Yes', 'Travel_Frequently', '32', '1125', 'Research & Development', '16', '1', 'Life Sciences', '2', 'Female', '72', '1', '1', 'Research Scientist', '1', 'Single', '3919', '4681', '1', 'Y', 'Yes', '22', '4', '2', '80', '0', '10', '5', '3', '10', '2', '6', '7'), ('No', 'Travel_Rarely', '42', '691', 'Sales', '8', '4', 'Marketing', '3', 'Male', '48', '3', '2', 'Sales Executive', '2', 'Married', '6825', '21173', '0', 'Y', 'No', '11', '3', '4', '80', '1', '10', '2', '3', '9', '7', '4', '2'), ('No', 'Travel_Rarely', '44', '477', 'Research & Development', '7', '4', 'Medical', '1', 'Female', '42', '2', '3', 'Healthcare Representative', '4', 'Married', '10248', '2094', '3', 'Y', 'No', '14', '3', '4', '80', '1', '24', '4', '3', '22', '6', '5', '17'), ('No', 'Travel_Rarely', '46', '705', 'Sales', '2', '4', 'Marketing', '2', 'Female', '83', '3', '5', 'Manager', '1', 'Single', '18947', '22822', '3', 'Y', 'No', '12', '3', '4', '80', '0', '22', '2', '2', '2', '2', '2', '1'), ('No', 'Travel_Rarely', '33', '924', 'Research & Development', '2', '3', 'Medical', '3', 'Male', '78', '3', '1', 'Laboratory Technician', '4', 'Single', '2496', '6670', '4', 'Y', 'No', '11', '3', '4', '80', '0', '7', '3', '3', '1', '1', '0', '0'), ('No', 'Travel_Rarely', '44', '1459', 'Research & Development', '10', '4', 'Other', '4', 'Male', '41', '3', '2', 'Healthcare Representative', '4', 'Married', '6465', '19121', '2', 'Y', 'Yes', '13', '3', '4', '80', '0', '9', '5', '4', '4', '2', '1', '3'), ('No', 'Travel_Rarely', '30', '125', 'Research & Development', '9', '2', 'Medical', '4', 'Male', '83', '2', '1', 'Laboratory Technician', '3', 'Single', '2206', '16117', '1', 'Y', 'No', '13', '3', '1', '80', '0', '10', '5', '3', '10', '0', '1', '8'), ('Yes', 'Travel_Rarely', '39', '895', 'Sales', '5', '3', 'Technical Degree', '4', 'Male', '56', '3', '2', 'Sales Representative', '4', 'Married', '2086', '3335', '3', 'Y', 'No', '14', '3', '3', '80', '1', '19', '6', '4', '1', '0', '0', '0'), ('Yes', 'Travel_Rarely', '24', '813', 'Research & Development', '1', '3', 'Medical', '2', 'Male', '61', '3', '1', 'Research Scientist', '4', 'Married', '2293', '3020', '2', 'Y', 'Yes', '16', '3', '1', '80', '1', '6', '2', '2', '2', '0', '2', '0'), ('No', 'Travel_Rarely', '43', '1273', 'Research & Development', '2', '2', 'Medical', '4', 'Female', '72', '4', '1', 'Research Scientist', '3', 'Divorced', '2645', '21923', '1', 'Y', 'No', '12', '3', '4', '80', '2', '6', '3', '2', '5', '3', '1', '4'), ('Yes', 'Travel_Rarely', '50', '869', 'Sales', '3', '2', 'Marketing', '1', 'Male', '86', '2', '1', 'Sales Representative', '3', 'Married', '2683', '3810', '1', 'Y', 'Yes', '14', '3', '3', '80', '0', '3', '2', '3', '3', '2', '0', '2'), ('No', 'Travel_Rarely', '35', '890', 'Sales', '2', '3', 'Marketing', '4', 'Female', '97', '3', '1', 'Sales Representative', '4', 'Married', '2014', '9687', '1', 'Y', 'No', '13', '3', '1', '80', '0', '2', '3', '3', '2', '2', '2', '2'), ('No', 'Travel_Rarely', '36', '852', 'Research & Development', '5', '4', 'Life Sciences', '2', 'Female', '82', '2', '1', 'Research Scientist', '1', 'Married', '3419', '13072', '9', 'Y', 'Yes', '14', '3', '4', '80', '1', '6', '3', '4', '1', '1', '0', '0'), ('No', 'Travel_Frequently', '33', '1141', 'Sales', '1', '3', 'Life Sciences', '3', 'Female', '42', '4', '2', 'Sales Executive', '1', 'Married', '5376', '3193', '2', 'Y', 'No', '19', '3', '1', '80', '2', '10', '3', '3', '5', '3', '1', '3'), ('No', 'Travel_Rarely', '35', '464', 'Research & Development', '4', '2', 'Other', '3', 'Male', '75', '3', '1', 'Laboratory Technician', '4', 'Divorced', '1951', '10910', '1', 'Y', 'No', '12', '3', '3', '80', '1', '1', '3', '3', '1', '0', '0', '0'), ('No', 'Travel_Rarely', '27', '1240', 'Research & Development', '2', '4', 'Life Sciences', '4', 'Female', '33', '3', '1', 'Laboratory Technician', '1', 'Divorced', '2341', '19715', '1', 'Y', 'No', '13', '3', '4', '80', '1', '1', '6', '3', '1', '0', '0', '0'), ('Yes', 'Travel_Rarely', '26', '1357', 'Research & Development', '25', '3', 'Life Sciences', '1', 'Male', '48', '1', '1', 'Laboratory Technician', '3', 'Single', '2293', '10558', '1', 'Y', 'No', '12', '3', '3', '80', '0', '1', '2', '2', '1', '0', '0', '1'), ('No', 'Travel_Frequently', '27', '994', 'Sales', '8', '3', 'Life Sciences', '4', 'Male', '37', '3', '3', 'Sales Executive', '3', 'Single', '8726', '2975', '1', 'Y', 'No', '15', '3', '4', '80', '0', '9', '0', '3', '9', '8', '1', '7'), ('No', 'Travel_Frequently', '30', '721', 'Research & Development', '1', '2', 'Medical', '3', 'Female', '58', '3', '2', 'Laboratory Technician', '4', 'Single', '4011', '10781', '1', 'Y', 'No', '23', '4', '4', '80', '0', '12', '2', '3', '12', '8', '3', '7'), ('Yes', 'Travel_Rarely', '41', '1360', 'Research & Development', '12', '3', 'Technical Degree', '2', 'Female', '49', '3', '5', 'Research Director', '3', 'Married', '19545', '16280', '1', 'Y', 'No', '12', '3', '4', '80', '0', '23', '0', '3', '22', '15', '15', '8'), ('No', 'Non-Travel', '34', '1065', 'Sales', '23', '4', 'Marketing', '2', 'Male', '72', '3', '2', 'Sales Executive', '3', 'Single', '4568', '10034', '0', 'Y', 'No', '20', '4', '3', '80', '0', '10', '2', '3', '9', '5', '8', '7'), ('No', 'Travel_Rarely', '37', '408', 'Research & Development', '19', '2', 'Life Sciences', '2', 'Male', '73', '3', '1', 'Research Scientist', '2', 'Married', '3022', '10227', '4', 'Y', 'No', '21', '4', '1', '80', '0', '8', '1', '3', '1', '0', '0', '0'), ('No', 'Travel_Frequently', '46', '1211', 'Sales', '5', '4', 'Marketing', '1', 'Male', '98', '3', '2', 'Sales Executive', '4', 'Single', '5772', '20445', '4', 'Y', 'Yes', '21', '4', '3', '80', '0', '14', '4', '3', '9', '6', '0', '8'), ('No', 'Travel_Rarely', '35', '1229', 'Research & Development', '8', '1', 'Life Sciences', '4', 'Male', '36', '4', '1', 'Laboratory Technician', '4', 'Married', '2269', '4892', '1', 'Y', 'No', '19', '3', '4', '80', '0', '1', '2', '3', '1', '0', '0', '1'), ('Yes', 'Travel_Rarely', '48', '626', 'Research & Development', '1', '2', 'Life Sciences', '1', 'Male', '98', '2', '3', 'Laboratory Technician', '3', 'Single', '5381', '19294', '9', 'Y', 'Yes', '13', '3', '4', '80', '0', '23', '2', '3', '1', '0', '0', '0'), ('Yes', 'Travel_Rarely', '28', '1434', 'Research & Development', '5', '4', 'Technical Degree', '3', 'Male', '50', '3', '1', 'Laboratory Technician', '3', 'Single', '3441', '11179', '1', 'Y', 'Yes', '13', '3', '3', '80', '0', '2', '3', '2', '2', '2', '2', '2'), ('No', 'Travel_Rarely', '44', '1488', 'Sales', '1', '5', 'Marketing', '2', 'Female', '75', '3', '2', 'Sales Executive', '1', 'Divorced', '5454', '4009', '5', 'Y', 'Yes', '21', '4', '3', '80', '1', '9', '2', '2', '4', '3', '1', '3'), ('No', 'Non-Travel', '35', '1097', 'Research & Development', '11', '2', 'Medical', '3', 'Male', '79', '2', '3', 'Healthcare Representative', '1', 'Married', '9884', '8302', '2', 'Y', 'Yes', '13', '3', '3', '80', '1', '10', '3', '3', '4', '0', '2', '3'), ('No', 'Travel_Rarely', '26', '1443', 'Sales', '23', '3', 'Marketing', '3', 'Female', '47', '2', '2', 'Sales Executive', '4', 'Married', '4157', '21436', '7', 'Y', 'Yes', '19', '3', '3', '80', '1', '5', '2', '2', '2', '2', '0', '0'), ('No', 'Travel_Frequently', '33', '515', 'Research & Development', '1', '2', 'Life Sciences', '1', 'Female', '98', '3', '3', 'Research Director', '4', 'Single', '13458', '15146', '1', 'Y', 'Yes', '12', '3', '3', '80', '0', '15', '1', '3', '15', '14', '8', '12'), ('No', 'Travel_Frequently', '35', '853', 'Sales', '18', '5', 'Life Sciences', '2', 'Male', '71', '3', '3', 'Sales Executive', '1', 'Married', '9069', '11031', '1', 'Y', 'No', '22', '4', '4', '80', '1', '9', '3', '2', '9', '8', '1', '8'), ('No', 'Travel_Rarely', '35', '1142', 'Research & Development', '23', '4', 'Medical', '3', 'Female', '30', '3', '1', 'Laboratory Technician', '1', 'Married', '4014', '16002', '3', 'Y', 'Yes', '15', '3', '3', '80', '1', '4', '3', '3', '2', '2', '2', '2'), ('No', 'Travel_Rarely', '31', '655', 'Research & Development', '7', '4', 'Life Sciences', '4', 'Male', '48', '3', '2', 'Laboratory Technician', '4', 'Divorced', '5915', '9528', '3', 'Y', 'No', '22', '4', '4', '80', '1', '10', '3', '2', '7', '7', '1', '7'), ('No', 'Travel_Rarely', '37', '1115', 'Research & Development', '1', '4', 'Life Sciences', '1', 'Male', '51', '2', '2', 'Manufacturing Director', '3', 'Divorced', '5993', '2689', '1', 'Y', 'No', '18', '3', '3', '80', '1', '7', '2', '4', '7', '5', '0', '7'), ('No', 'Travel_Rarely', '32', '427', 'Research & Development', '1', '3', 'Medical', '1', 'Male', '33', '3', '2', 'Manufacturing Director', '4', 'Married', '6162', '10877', '1', 'Y', 'Yes', '22', '4', '2', '80', '1', '9', '3', '3', '9', '8', '7', '8'), ('No', 'Travel_Frequently', '38', '653', 'Research & Development', '29', '5', 'Life Sciences', '4', 'Female', '50', '3', '2', 'Laboratory Technician', '4', 'Single', '2406', '5456', '1', 'Y', 'No', '11', '3', '4', '80', '0', '10', '2', '3', '10', '3', '9', '9'), ('No', 'Travel_Rarely', '50', '989', 'Research & Development', '7', '2', 'Medical', '2', 'Female', '43', '2', '5', 'Research Director', '3', 'Divorced', '18740', '16701', '5', 'Y', 'Yes', '12', '3', '4', '80', '1', '29', '2', '2', '27', '3', '13', '8'), ('No', 'Travel_Rarely', '59', '1435', 'Sales', '25', '3', 'Life Sciences', '1', 'Female', '99', '3', '3', 'Sales Executive', '1', 'Single', '7637', '2354', '7', 'Y', 'No', '11', '3', '4', '80', '0', '28', '3', '2', '21', '16', '7', '9'), ('No', 'Travel_Rarely', '36', '1223', 'Research & Development', '8', '3', 'Technical Degree', '3', 'Female', '59', '3', '3', 'Healthcare Representative', '3', 'Divorced', '10096', '8202', '1', 'Y', 'No', '13', '3', '2', '80', '3', '17', '2', '3', '17', '14', '12', '8'), ('No', 'Travel_Rarely', '55', '836', 'Research & Development', '8', '3', 'Medical', '4', 'Female', '33', '3', '4', 'Manager', '3', 'Divorced', '14756', '19730', '2', 'Y', 'Yes', '14', '3', '3', '80', '3', '21', '2', '3', '5', '0', '0', '2'), ('No', 'Travel_Frequently', '36', '1195', 'Research & Development', '11', '3', 'Life Sciences', '2', 'Male', '95', '2', '2', 'Manufacturing Director', '2', 'Single', '6499', '22656', '1', 'Y', 'No', '13', '3', '3', '80', '0', '6', '3', '3', '6', '5', '0', '3'), ('No', 'Travel_Rarely', '45', '1339', 'Research & Development', '7', '3', 'Life Sciences', '2', 'Male', '59', '3', '3', 'Research Scientist', '1', 'Divorced', '9724', '18787', '2', 'Y', 'No', '17', '3', '3', '80', '1', '25', '2', '3', '1', '0', '0', '0'), ('No', 'Travel_Frequently', '35', '664', 'Research & Development', '1', '3', 'Medical', '2', 'Male', '79', '3', '1', 'Research Scientist', '1', 'Married', '2194', '5868', '4', 'Y', 'No', '13', '3', '4', '80', '1', '5', '2', '2', '3', '2', '1', '2'), ('Yes', 'Travel_Rarely', '36', '318', 'Research & Development', '9', '3', 'Medical', '4', 'Male', '79', '2', '1', 'Research Scientist', '3', 'Married', '3388', '21777', '0', 'Y', 'Yes', '17', '3', '1', '80', '1', '2', '0', '2', '1', '0', '0', '0'), ('No', 'Travel_Frequently', '59', '1225', 'Sales', '1', '1', 'Life Sciences', '1', 'Female', '57', '2', '2', 'Sales Executive', '3', 'Single', '5473', '24668', '7', 'Y', 'No', '11', '3', '4', '80', '0', '20', '2', '2', '4', '3', '1', '3'), ('No', 'Travel_Rarely', '29', '1328', 'Research & Development', '2', '3', 'Life Sciences', '3', 'Male', '76', '3', '1', 'Research Scientist', '2', 'Married', '2703', '4956', '0', 'Y', 'No', '23', '4', '4', '80', '1', '6', '3', '3', '5', '4', '0', '4'), ('No', 'Travel_Rarely', '31', '1082', 'Research & Development', '1', '4', 'Medical', '3', 'Male', '87', '3', '1', 'Research Scientist', '2', 'Single', '2501', '18775', '1', 'Y', 'No', '17', '3', '2', '80', '0', '1', '4', '3', '1', '1', '1', '0'), ('No', 'Travel_Rarely', '32', '548', 'Research & Development', '1', '3', 'Life Sciences', '2', 'Male', '66', '3', '2', 'Research Scientist', '2', 'Married', '6220', '7346', '1', 'Y', 'No', '17', '3', '2', '80', '2', '10', '3', '3', '10', '4', '0', '9'), ('No', 'Travel_Rarely', '36', '132', 'Research & Development', '6', '3', 'Life Sciences', '2', 'Female', '55', '4', '1', 'Laboratory Technician', '4', 'Married', '3038', '22002', '3', 'Y', 'No', '12', '3', '2', '80', '0', '5', '3', '3', '1', '0', '0', '0'), ('No', 'Travel_Rarely', '31', '746', 'Research & Development', '8', '4', 'Life Sciences', '3', 'Female', '61', '3', '2', 'Manufacturing Director', '4', 'Single', '4424', '20682', '1', 'Y', 'No', '23', '4', '4', '80', '0', '11', '2', '3', '11', '7', '1', '8'), ('No', 'Travel_Rarely', '35', '776', 'Sales', '1', '4', 'Marketing', '3', 'Male', '32', '2', '2', 'Sales Executive', '1', 'Single', '4312', '23016', '0', 'Y', 'No', '14', '3', '2', '80', '0', '16', '2', '3', '15', '13', '2', '8'), ('No', 'Travel_Rarely', '45', '193', 'Research & Development', '6', '4', 'Other', '4', 'Male', '52', '3', '3', 'Research Director', '1', 'Married', '13245', '15067', '4', 'Y', 'Yes', '14', '3', '2', '80', '0', '17', '3', '4', '0', '0', '0', '0'), ('No', 'Travel_Rarely', '37', '397', 'Research & Development', '7', '4', 'Medical', '1', 'Male', '30', '3', '3', 'Research Director', '3', 'Single', '13664', '25258', '4', 'Y', 'No', '13', '3', '1', '80', '0', '16', '3', '4', '5', '2', '0', '2'), ('No', 'Travel_Rarely', '46', '945', 'Human Resources', '5', '2', 'Medical', '2', 'Male', '80', '3', '2', 'Human Resources', '2', 'Divorced', '5021', '10425', '8', 'Y', 'Yes', '22', '4', '4', '80', '1', '16', '2', '3',

In [6]:
sqliteConnection = sqlite3.connect('sql.db')
    #sqliteConnection = sqlite3.connect('sql.db')
cursor = sqliteConnection.cursor()

In [7]:
pd.read_sql_query('''SELECT * FROM table_HR''',sqliteConnection)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,...,1,80,0,6,3,4,4,3,1,2

In [8]:
pd.read_sql_query('''SELECT Attrition,ROUND((COUNT(*) * 100.0 / SUM(COUNT(*)) OVER ()), 1)
                    AS Attrition_rate FROM table_HR GROUP BY Attrition order by Attrition_rate ''',sqliteConnection)

  Attrition  Attrition_rate
0       Yes            16.1
1        No            83.9

#### Sample Output

![image](https://api-v4.skyprepapp.com/public_api/da/857886?view_key=eyJvYmplY3RfdHlwZSI6ImFydGljbGUiLCJvYmplY3RfaWQiOjg1Nzg4NiwiaG1hYyI6ImUyNGU0YWRhNWQwMDkxNWE2NWNiY2EwNGFlNDNiMTBlYmYyNWY0YzAiLCJleHBpcmVzX2F0Ijo0ODkxMzgxMTk5LCJvdHRfdG9rZW4iOm51bGx9)

Observation:-

The table presents attrition data with two categories:

1. 16.1% of employees have left the organization (attrition = true).
2. 83.9% of employees have remained with the organization (attrition = false).

This indicates that the majority of employees are retained, while a smaller portion has exited.

#### Find Attrition by Gender

In [9]:
### Implement code
pd.read_sql_query('''SELECT Attrition, Gender, COUNT(*) as Count_gender,  ROUND((COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (partition by Gender)), 1)
                    AS Attrition_by_gender FROM table_HR GROUP BY Attrition, Gender order by Attrition_by_gender ''',sqliteConnection)

  Attrition  Gender  Count_gender  Attrition_by_gender
0       Yes  Female            87                 14.8
1       Yes    Male           150                 17.0
2        No    Male           732                 83.0
3        No  Female           501                 85.2

Observations:

1. Males have a slightly higher attrition rate (17.0%) compared to females (14.8%).
2. The majority of both genders remain with the organization.
More males have left in absolute numbers (150) compared to females (87), likely due to a larger male employee population.

#### Sample output

![image](https://api-v4.skyprepapp.com/public_api/da/857882?view_key=eyJvYmplY3RfdHlwZSI6ImFydGljbGUiLCJvYmplY3RfaWQiOjg1Nzg4MiwiaG1hYyI6IjM1NDU5N2E4MjZmMTMxNWFhMTA4NzFiYTFkZjQ5YjBhNTYyOWYwMzgiLCJleHBpcmVzX2F0Ijo0ODkxMzgxMTk5LCJvdHRfdG9rZW4iOm51bGx9)

#### Find Attrition by Dept

In [10]:
#### Find Attrition by Gender### Implement code
pd.read_sql_query('''SELECT Department, Attrition, Count(*) as Department_attrition
                    FROM table_HR GROUP BY Department, Attrition order by Department''',sqliteConnection)

               Department Attrition  Department_attrition
0         Human Resources        No                    51
1         Human Resources       Yes                    12
2  Research & Development        No                   828
3  Research & Development       Yes                   133
4                   Sales        No                   354
5                   Sales       Yes                    92

Observations:

1. The Research & Development department has the highest number of employees (both retained and attrited), with 133 employees leaving.
2. The Sales department has 92 employees leaving, indicating a relatively high attrition count.
3. The Human Resources department has the lowest attrition in absolute numbers (12 employees).
Across all departments, the majority of employees remain with the company.

#### Sample Output

<img src="https://api-v4.skyprepapp.com/public_api/da/857884?view_key=eyJvYmplY3RfdHlwZSI6ImFydGljbGUiLCJvYmplY3RfaWQiOjg1Nzg4NCwiaG1hYyI6IjdmOTA4NzJjODZmYTgxOGUyMzkyYTBlZjhjYjljNjA4ZGM3NjkzMWYiLCJleHBpcmVzX2F0Ijo0ODkxMzgxMTk5LCJvdHRfdG9rZW4iOm51bGx9" width="450" height="450">

#### Find Attrition by Age Groups

In [11]:
pd.read_sql_query('''SELECT Attrition, CASE
         WHEN Age < 30 THEN 'Under 30'
         WHEN Age BETWEEN 30 AND 39 THEN '30-40'
         WHEN Age BETWEEN 40 AND 49 THEN '40-50'
         ELSE 'Over 50'
         END AS Age_group,
         COUNT(*) as num,
         ROUND((COUNT(*) * 100.0 / SUM(COUNT(*))
         OVER (PARTITION  by CASE
                              WHEN Age < 30 THEN 'Under 30'
                              WHEN Age BETWEEN 30 AND 39 THEN '30-40'
                              WHEN Age BETWEEN 40 AND 49 THEN '40-50'
                              ELSE 'Over 50'
                              END )),2) as percent_by_age
         FROM table_HR GROUP BY Attrition, CASE
                                         WHEN Age < 30 THEN 'Under 30'
                                         WHEN Age BETWEEN 30 AND 39 THEN '30-40'
                                         WHEN Age BETWEEN 40 AND 49 THEN '40-50'
                                         ELSE 'Over 50'
                                         END order by percent_by_age desc''',sqliteConnection)

  Attrition Age_group  num  percent_by_age
0        No     40-50  315           90.26
1        No   Over 50  150           86.71
2        No     30-40  533           85.69
3        No  Under 30  235           72.09
4       Yes  Under 30   91           27.91
5       Yes     30-40   89           14.31
6       Yes   Over 50   23           13.29
7       Yes     40-50   34            9.74

Observation:-
1. Younger employees (Under 30) are the most likely to leave, possibly due to career exploration, job dissatisfaction, or better opportunities.

2. Middle-aged employees (30-50) are more stable, likely due to career growth, financial commitments, or job satisfaction.

3. Older employees (Over 50) have low attrition, possibly due to job security, nearing retirement, or fewer external job opportunities.

#### Sample Output

![image](https://api-v4.skyprepapp.com/public_api/da/857885?view_key=eyJvYmplY3RfdHlwZSI6ImFydGljbGUiLCJvYmplY3RfaWQiOjg1Nzg4NSwiaG1hYyI6IjcwNGVlOWIwYzg1MmMwNmNhODg0NmYyZDFlNWE3OTU1MTFhMGVmYWYiLCJleHBpcmVzX2F0Ijo0ODkxMzgxMTk5LCJvdHRfdG9rZW4iOm51bGx9)

#### Find Attrition by Monthly Income

In [12]:
### Implement code
pd.read_sql_query('''SELECT Department, JobLevel, Round(Avg(MonthlyIncome),1) as avg_income,
                     ROUND(AVG(CASE WHEN Attrition = 'Yes' THEN MonthlyIncome END), 1) AS attrition_avg_income,
                     ROUND(AVG(CASE WHEN Attrition = 'Yes' THEN MonthlyIncome END) - AVG(MonthlyIncome), 1) AS difference
                    FROM table_HR
                    GROUP BY Department, JobLevel
                    HAVING AVG(CASE WHEN Attrition = 'Yes' THEN MonthlyIncome END) IS NOT NULL
                    order by Department''',sqliteConnection)

,Department,JobLevel,avg_income,attrition_avg_income,difference
0,Human Resources,1,2733.2,2415.7,-317.5
1,Human Resources,3,9623.0,10216.0,593.0
2,Research & Development,1,2840.1,2687.4,-152.7
3,Research & Development,2,5291.2,5372.0,80.8
4,Research & Development,3,10170.5,9503.8,-666.6
5,Research & Development,4,15634.7,12169.0,-3465.7
6,Research & Development,5,19218.5,19550.0,331.5
7,Sales,1,2506.7,2373.4,-133.3
8,Sales,2,5746.1,5917.0,170.9
9,Sales,3,9282.3,9202.8,-79.5
10,Sales,4,15166.3,13395.8,-1770.5
11,Sales,5,19088.0,19334.5,246.5

1. Lower-level employees tend to leave with lower salaries than their department's average. This could indicate dissatisfaction with pay at the entry-level.

2. Mid-level employees in some departments experience salary drops upon leaving, possibly due to job market conditions or role adjustments.

3. Higher-level employees (Job Level 5) leaving tend to have competitive salaries, suggesting that attrition at senior levels might be due to better opportunities rather than dissatisfaction.

4. The largest negative income differences are in R&D (Job Level 4) and Sales (Job Level 4), indicating that higher-level attrition in these departments might come with pay cuts.

#### Sample Output

![image](https://api-v4.skyprepapp.com/public_api/da/857883?view_key=eyJvYmplY3RfdHlwZSI6ImFydGljbGUiLCJvYmplY3RfaWQiOjg1Nzg4MywiaG1hYyI6Ijg3NTU4ZDU1ZjRjN2U1YWI3ODQzYjM1NzFkNjBjMjEwNGY5NWI5ODUiLCJleHBpcmVzX2F0Ijo0ODkxMzgxMTk5LCJvdHRfdG9rZW4iOm51bGx9)

#### Find Attrition by Years At Company

In [13]:
### Implement code
pd.read_sql_query('''SELECT
    CASE
        WHEN YearsAtCompany < 2 THEN 'New Hires'
        WHEN YearsAtCompany BETWEEN 2 AND 5 THEN '2-5 years'
        WHEN YearsAtCompany BETWEEN 6 AND 10 THEN '6-10 years'
        WHEN YearsAtCompany BETWEEN 11 AND 20 THEN '11-20 years'
        ELSE 'Over 20 years'
    END AS tenure_years,
    COUNT(*) AS num,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 1) AS percent
FROM table_HR where Attrition = 'Yes'
GROUP BY
    CASE
        WHEN YearsAtCompany < 2 THEN 'New Hires'
        WHEN YearsAtCompany BETWEEN 2 AND 5 THEN '2-5 years'
        WHEN YearsAtCompany BETWEEN 6 AND 10 THEN '6-10 years'
        WHEN YearsAtCompany BETWEEN 11 AND 20 THEN '11-20 years'
        ELSE 'Over 20 years'
    END
ORDER BY num DESC''',sqliteConnection)

    tenure_years  num  percent
0      2-5 years   87     36.7
1      New Hires   75     31.6
2     6-10 years   55     23.2
3    11-20 years   12      5.1
4  Over 20 years    8      3.4

Observation:-
1. Early-career employees (New Hires & 2-5 years) are the most likely to leave, indicating that retention strategies should focus on engagement, career growth, and satisfaction within the first 5 years.

2. Mid-career employees (6-10 years) still experience some attrition, but the rate declines significantly, suggesting they find more stability.

3. Long-tenured employees (11+ years) have very low attrition, meaning that those who stay beyond a decade are likely to remain long-term.

#### Sample Output

![image](https://api-v4.skyprepapp.com/public_api/da/857881?view_key=eyJvYmplY3RfdHlwZSI6ImFydGljbGUiLCJvYmplY3RfaWQiOjg1Nzg4MSwiaG1hYyI6IjFhYmY3NGI4MzQ1NzViMWZkNDJlMjcwYTUyOTQ0OWQwZjJjMjhmNWUiLCJleHBpcmVzX2F0Ijo0ODkxMzgxMTk5LCJvdHRfdG9rZW4iOm51bGx9)

#### Continue using SQL to explore main reasons for attrition (3 pts), For example:
- Why do more people over 50 years old leave the company than people who aged 40-50?
- Why do people with higher pay still leave the company?
- Which factors drive employees who work at company less than 5 years to leave?

In [14]:
pd.read_sql_query('''SELECT  CASE
                            WHEN Age BETWEEN 40 AND 50 THEN '40-50'
                            ELSE 'Over 50'
                        END AS Age_group,OverTime,
                        AVG(EnvironmentSatisfaction),
                        AVG(JobSatisfaction),
                        AVG(PercentSalaryHike),
                        AVG(PerformanceRating),
                        AVG(RelationshipSatisfaction),
                        AVG(MonthlyIncome),
                        AVG(WorkLifeBalance),
                        AVG(NumCompaniesWorked),
                        AVG(YearsSinceLastPromotion)
                    FROM table_HR where Attrition='Yes'
                    GROUP BY  Age_group, OverTime
                    ''', sqliteConnection)

,Age_group,OverTime,AVG(EnvironmentSatisfaction),AVG(JobSatisfaction),AVG(PercentSalaryHike),AVG(PerformanceRating),AVG(RelationshipSatisfaction),AVG(MonthlyIncome),AVG(WorkLifeBalance),AVG(NumCompaniesWorked),AVG(YearsSinceLastPromotion)
0,40-50,No,2.000000,2.352941,15.058824,3.176471,2.823529,7708.000000,2.823529,3.941176,3.588235
1,40-50,Yes,2.500000,2.545455,13.818182,3.090909,2.909091,6377.500000,2.454545,3.318182,1.863636
2,Over 50,No,2.387097,2.365591,14.752688,3.118280,2.462366,4385.903226,2.591398,2.795699,1.709677
3,Over 50,Yes,2.600000,2.561905,15.676190,3.200000,2.619048,4336.295238,2.733333,2.828571,1.904762

Observation:-
1. Employees over 50 (No Overtime) earn 4,385.90, while those aged 40-50 (No Overtime) earn 7,708.00. Even though older employees received higher salary hikes (15.67%), their base salaries remain significantly lower.
2. Employees over 50 working overtime have an even lower work-life balance, which could lead to burnout. Employees aged 40-50 (No Overtime) have a higher job satisfaction score (2.35) compared to over 50 (No Overtime) at 2.36.
 Over 50 (Overtime) have slightly better job satisfaction (2.56) but still not significantly high.
3. Employees aged 40-50 (No Overtime) have not been promoted in ~3.59 years, whereas those over 50 (No Overtime) have not been promoted in ~1.7 years.
This suggests that even though promotions happen, they do not result in significant salary increases, which may lead to frustration.

4. Employees aged 40-50 have better relationship satisfaction (2.82-2.90) than those over 50 (2.46-2.61).Performance ratings are similar (3.17 for 40-50 vs. 3.15 for over 50), meaning older employees are performing well but may feel undervalued.

Q.2 Why do people with higher pay still leave the company?

In [30]:
pd.read_sql_query('''
       WITH IncomePercentiles AS (
    SELECT
        MonthlyIncome,
        NTILE(4) OVER (ORDER BY MonthlyIncome) AS IncomeGroup
    FROM table_HR
    WHERE MonthlyIncome > (SELECT AVG(MonthlyIncome) FROM table_HR)
)
SELECT
    CASE
        WHEN ip.IncomeGroup = 1 THEN 'Low (0-25th Percentile)'
        WHEN ip.IncomeGroup = 2 THEN 'Medium (25th-50th Percentile)'
        WHEN ip.IncomeGroup = 3 THEN 'High (50th-75th Percentile)'
        WHEN ip.IncomeGroup = 4 THEN 'Very High (75th-100th Percentile)'
    END AS IncomeCategory,
    t.Attrition,
    Avg(t.MonthlyIncome),
    Avg(t.JobSatisfaction),
    Avg(t.WorkLifeBalance),
    Avg(t.YearsSinceLastPromotion),
    Avg(t.PerformanceRating)

FROM table_HR t
JOIN IncomePercentiles ip ON t.MonthlyIncome = ip.MonthlyIncome
WHERE t.MonthlyIncome > (SELECT AVG(MonthlyIncome) FROM table_HR)
GROUP BY IncomeCategory, t.Attrition;
                    ''', sqliteConnection)

,IncomeCategory,Attrition,Avg(t.MonthlyIncome),Avg(t.JobSatisfaction),Avg(t.WorkLifeBalance),Avg(t.YearsSinceLastPromotion),Avg(t.PerformanceRating)
0,High (50th-75th Percentile),No,12698.710526,2.736842,2.824561,3.166667,3.184211
1,High (50th-75th Percentile),Yes,12175.727273,2.636364,2.181818,7.363636,3.000000
2,Low (0-25th Percentile),No,7201.870690,2.887931,2.775862,1.836207,3.094828
3,Low (0-25th Percentile),Yes,7352.357143,2.500000,2.785714,1.642857,3.142857
4,Medium (25th-50th Percentile),No,9521.038462,2.769231,2.778846,3.759615,3.153846
5,Medium (25th-50th Percentile),Yes,9762.840000,2.360000,2.800000,3.560000,3.120000
6,Very High (75th-100th Percentile),No,18177.721311,2.696721,2.762295,4.786885,3.147541
7,Very High (75th-100th Percentile),Yes,19463.800000,2.400000,3.000000,7.200000,3.000000

Observation:-
1. Employees who did not leave have slightly higher average salaries than those who left.
2. Employees with lower job satisfaction are more likely to leave, regardless of salary.
3. Poor Work-Life Balance contributes to attrition, especially in High & Low percentiles.
4. Long promotion gaps strongly correlate with attrition.Even high salaries do not retain employees if promotions are delayed.
5.  Employees with similar performance ratings still leave, indicating attrition is driven more by promotion delays & job satisfaction than performance.

Observation

Q.3) Which factors drive employees who work at company less than 5 years to leave?

In [ ]:
pd.read_sql_query('''
SELECT
    YearsAtCompany,Attrition,
    COUNT(*) AS Number_of_Employees,
    AVG(MonthlyIncome) AS Average_Monthly_Income,
    AVG(JobLevel) AS Average_JobLevel,
    AVG(JobSatisfaction) AS Average_JobSatisfaction,
    AVG(WorkLifeBalance) AS Average_WorkLifeBalance
FROM table_HR
WHERE YearsAtCompany < 5
GROUP BY YearsAtCompany,Attrition
ORDER BY Attrition
''', sqliteConnection)

,YearsAtCompany,Attrition,Number_of_Employees,Average_Monthly_Income,Average_JobLevel,Average_JobSatisfaction,Average_WorkLifeBalance
0,0,No,28,4715.357143,1.678571,2.785714,2.750000
1,1,No,112,5479.991071,1.776786,2.821429,2.812500
2,2,No,100,5168.460000,1.680000,2.950000,2.790000
3,3,No,108,5326.388889,1.740741,2.703704,2.777778
4,4,No,91,5361.780220,1.802198,2.582418,2.670330
5,0,Yes,16,3060.250000,1.250000,2.250000,2.750000
6,1,Yes,59,3165.152542,1.305085,2.525424,2.694915
7,2,Yes,27,4157.407407,1.333333,2.592593,2.518519
8,3,Yes,20,3743.100000,1.350000,2.000000,2.950000
9,4,Yes,19,3903.368421,1.421053,2.684211,2.421053

Observation:-
1. Employees who left had significantly lower average monthly income and job levels than those who stayed.
2. Employees who left had lower work-life balance scores.
3. New hires with lower salaries are more likely to leave early.